### ISSUE TITLE
Add-DbaAgDatabase example 5 spills out of code block

### ISSUE THREAD

**Issue by luke-mckee-ol** [dataplat/docs#84]
![image](https://github.com/dataplat/docs/assets/75047659/fd3a5b29-cdbf-4947-82d6-f2a9be080d9b)

See `Example 5` on [Add-DbaAgDatabase](https://docs.dbatools.io/Add-DbaAgDatabase)

I'm happy to contrib to fix it, but I'm not sure how it's meant to be handled or what engine you're using to generate docs and can't find an example of another command that utilizes a `;`. Don't use this lib super often so not so familiar. If you can link me one I'll action it when I get a minute.

**Comment by niphlod** [comment]
hi @luke-mckee-ol , thanks for the report. Frankly, it's not the `;` ... how do I know this ? Try zooming back, everything stays the same... we could fix what translates the inline help to the base data that "generates the page" but frankly the problem here is in the "source data", which is the function ... the example 5 is just too damn long to be readable, and I guess it could benefit from a refactor splitting it on multiple lines directly making a pr against https://github.com/dataplat/dbatools/blob/master/public/Add-DbaAgDatabase.ps1. 
That'll serve everybody: fix the site AND the inline help on the various IDEs.
We should strive to have examples lines with 100/120 chars long at top.

**Comment by luke-mckee-ol** [comment]
Thanks @niphlod , I've updated the title to reflect your feedback.

I will take a shot at making the example multiples lines when I get an extra minute if no one beats me to it :)

**Comment by niphlod** [comment]
forgot about this but it seems still an issue, I'll see if I can fix it in the next few days
